-- AlterTable
ALTER TABLE "anexo" ALTER COLUMN "criado_em" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "atualizado_em" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "criterio_avaliacao" ADD COLUMN     "atualizado_em" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "usuario" ALTER COLUMN "criado_em" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "atualizado_em" SET DEFAULT CURRENT_TIMESTAMP;
