import type { CategoriaProjeto } from '@prisma/client';

export const CategoriaProjetoMapper: Record<CategoriaProjeto, string> = {
  CATEGORIA_PADRAO: 'Categoria padrão',
  DESENVOLVIMENTO_CIENTIFICO_INSTITUCIONAL_E_TECNOLOGICO:
    'Desenvolvimento científico, institucional e tecnológico',
  FOMENTO_A_PESQUISA_CIENTIFICA_E_TECNOLOGICA: 'Fomento à pesquisa científica e tecnológica',
  ESTUDOS_DE_CTI: 'Estudos de CT&I (Ciência, Tecnologia e Inovação)',
  SAUDE: 'Saúde',
  BIOTECNOLOGIA: 'Biotecnologia',
  NANOTECNOLOGIA: 'Nanotecnologia',
  BIOCOMBUSTIVEIS: 'Biocombustíveis',
  ENERGIA_ELETRICA: 'Energia elétrica',
  ENERGIAS_RENOVAVEIS: 'Energias renováveis',
  PETROLEO_E_GAS: 'Petróleo e gás',
  AGRONEGOCIO: 'Agronegócio',
  BIODIVERSIDADE_E_RECURSOS_NATURAIS: 'Biodiversidade e recursos naturais',
  RECURSOS_HIDRICOS: 'Recursos hídricos',
  SEMIARIDO: 'Semiárido',
  AQUICULTURA_E_PESCA: 'Aquicultura e pesca',
  METEOROLOGIA_E_MUDANCAS_CLIMATICAS: 'Meteorologia e mudanças climáticas',
  TECNOLOGIA_INDUSTRIAL: 'Tecnologia industrial',
  SEGURANCA_PUBLICA: 'Segurança pública',
  TECNOLOGIA_SOCIAL: 'Tecnologia social',
  DESIGN: 'Design',
  TECNOLOGIA_INCLUSIVA: 'Tecnologia inclusiva',
  ECONOMIA_CRIATIVA: 'Economia criativa',
  INOVACAO: 'Inovação',
  PROGRAMAS_DE_COMPUTADOR: 'Programas de computador',
  MODELOS_DE_UTILIDADE: 'Modelos de utilidade',
  NOVA_CULTIVAR: 'Nova cultivar',
  CULTIVAR_DERIVADA: 'Cultivar derivada',
  AGROINDUSTRIA: 'Agroindústria',
  DESENHO_INDUSTRIAL: 'Desenho industrial',
  TOPOGRAFIA_DE_CIRCUITO_INDUSTRIAL: 'Topografia de circuito industrial',
  DESENVOLVIMENTO_DE_TECNOLOGIA: 'Desenvolvimento de tecnologia',
  DESENVOLVIMENTO_DE_PRODUTO: 'Desenvolvimento de produto',
  DESENVOLVIMENTO_DE_PROCESSO: 'Desenvolvimento de processo',
  APERFEICOAMENTO_DE_TECNOLOGIA: 'Aperfeiçoamento de tecnologia',
  APERFEICOAMENTO_DE_PROCESSO: 'Aperfeiçoamento de processo',
  APERFEICOAMENTO_DE_PRODUTO: 'Aperfeiçoamento de produto',
  SERVICO_INOVADOR: 'Serviço inovador',
  PESQUISA_CIENTIFICA: 'Pesquisa científica',
  PESQUISA_BASICA: 'Pesquisa básica',
  PESQUISA_APLICADA: 'Pesquisa aplicada',
};
